### ISSUE TITLE
CheckFilesystemFreeSpace may return wrong value

### ISSUE THREAD

**Issue by mkofahl** [openthinclient/openthinclient-manager#29]
Having the otc directories mounted on separate volumes, the setup routine may fail because the free disk space is calculated from `getRoot()`:
https://github.com/openthinclient/openthinclient-manager/blob/b1a6601d9ba5a2b695867662d3ba206b5e09cf8b/advisor/src/main/java/org/openthinclient/advisor/check/CheckFilesystemFreeSpace.java#L41

**Comment by fernanfs** [comment]
Thank you for your contribution. The Change has been integrated into the current develop branch.
